"""assessment reference text for pronunciation analysis

Revision ID: bba2e2b63f60
Revises: c157ef0c6268
Create Date: 2026-09-30 08:34:03.448902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bba2e2b63f60'
down_revision: Union[str, None] = 'c157ef0c6268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('reference_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'reference_text')
    # ### end Alembic commands ###
