"""kb document status and failure reason

Revision ID: c157ef0c6268
Revises: 6eede75ba2db
Create Date: 2026-09-30 03:02:37.041813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c157ef0c6268'
down_revision: Union[str, None] = '6eede75ba2db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required here: existing rows (from before this
    # column existed) must get a real value, not fail the NOT NULL
    # constraint. Anything already in the table was, by definition, usable
    # before this migration — i.e. already indexed — so 'INDEXED' is the
    # honest default, not a guess.
    op.add_column(
        'knowledge_documents',
        sa.Column('status', sa.String(length=20), nullable=False, server_default='INDEXED'),
    )
    op.add_column('knowledge_documents', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_documents_status'), table_name='knowledge_documents')
    op.drop_column('knowledge_documents', 'failure_reason')
    op.drop_column('knowledge_documents', 'status')
    # ### end Alembic commands ###
